version: "3.8"
services:
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
      POSTGRES_DB: golang_l0
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "3001:5432"
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ..:/var/www/golang
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - app
        - postgres
  nats-streaming:
    image: nats-streaming:0.25.6
    ports:
      - "4222:4222"  # Порт для клиентов NATS
      - "8222:8222"  # Порт для мониторинга
    command: [
      "-p", "4222",    # порт для клиентов NATS
      "-m", "8222",    # порт для мониторинга
      "-cluster", "nats://0.0.0.0:6222",  # адрес кластера
    ]
  app:
    build: ./app
    volumes:
      - ..:/var/www/golang
    ports:
      - "9000:9000"
    depends_on:
      - postgres
networks:
  golang_l0_network:
    ipam:
      config:
        - subnet: '192.168.88.0/24'
volumes:
  postgres:
